# Generated by Django 4.2.5 on 2023-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='Ключ для верификации почты'),
        ),
    ]
