# Generated by Django 4.2.4 on 2023-09-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='slug', max_length=150, unique=True, verbose_name='slug'),
        ),
    ]
