# Generated by Django 4.2.4 on 2023-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100, verbose_name='Страна')),
                ('tin', models.CharField(max_length=100, verbose_name='ИНН')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контактные данные',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
