# Generated by Django 4.2.4 on 2023-09-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacts_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='county',
            new_name='country',
        ),
    ]
