# Generated by Django 4.2.4 on 2023-09-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
    ]
